# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 150ee793e99e1ee97e33fa09fda4096b18f72e5a9de35b51d78085ee5a277e503825bb466daeaadc83e5835d880a9998dbdec2a3656acf9f3d35af2fe97eb0cc

test:
  secret_key_base: 03a9504f779594846da93ab0b08d7663b3e39472d202a1274d34be07725a75b32af202867372bfd614896fc82dcec9e7bc75d126cb665a9b8a4db659a9a99563

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
